model:
  NAME: BasePartSeg
  encoder_args:
    NAME: PointMambaEncoder
    in_channels: 7
    embed_dim: 192
    groups: 1
    res_expansion: 1.0
    activation: "relu"
    bias: False
    use_xyz: True
    normalize: "anchor"
    dim_expansion: [ 1, 1, 2, 1 ]
    pre_blocks: [ 1, 1, 1, 1 ]
    mamba_blocks: [ 1, 1, 2, 2 ]
    pos_blocks: [ 0, 0, 0, 0 ]
    k_neighbors: [ 12, 12, 12, 12 ]
    reducers: [ 2, 2, 2, 2 ]
    rms_norm: True
    residual_in_fp32: True
    fused_add_norm: True
    bimamba_type: "v2"
    drop_path_rate: 0.1
    mamba_pos: True
    mamba_layers_orders: [ "xyz", "xzy", "yxz", "yzx", "zxy", "zyx" ]
    use_order_prompt: True
    prompt_num_per_order: 6

  decoder_args:
    NAME: PointMambaPartDecoder
    encoder_channel_list: [ 192, 192, 192, 384, 384 ]
    decoder_channel_list: [ 384, 192, 192, 192 ]
    decoder_blocks: [ 1, 1, 1, 1 ]
    mamba_blocks: [ 0, 0, 0, 0 ]
    mamba_layers_orders: [ ]

  cls_args:
    NAME: SegHead
    global_feat: max,avg  # append global feature to each point feature
    num_classes: 50
    in_channels: null
    norm_args:
      norm: 'bn'

# Optimizer
batch_size: 8
dataloader:
  num_workers: 6

lr: 0.0001
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05

warmup_epochs: 5
min_lr: 1.0e-5
# scheduler
epochs: 300
sched: multistep
decay_epochs: [210, 270]
decay_rate: 0.5

datatransforms:
  train: [PointsToTensor, PointCloudScaling,PointCloudCenterAndNormalize,PointCloudJitter,ChromaticDropGPU]
  val: [PointsToTensor, PointCloudCenterAndNormalize]
  kwargs:
    jitter_sigma: 0.001
    jitter_clip: 0.005
    scale: [0.8, 1.2]
    gravity_dim: 1
    angle: [0, 1.0, 0]