model:
  NAME: BaseSeg
  test_crop: 24576
  encoder_args:
    NAME: PointMambaEncoder
    in_channels: 7
    embed_dim: 96
    groups: 1
    res_expansion: 1.0
    activation: "relu"
    bias: False
    use_xyz: True
    normalize: "anchor"
    dim_expansion: [ 1, 2, 2, 2 ]
    pre_blocks: [ 1, 1, 1, 1 ]
    mamba_blocks: [ 1, 2, 2, 4 ]
    pos_blocks: [ 0, 0, 0, 0 ]
    k_neighbors: [ 12, 12, 12, 12 ]
    reducers: [ 4, 4, 2, 2 ]
    rms_norm: True
    residual_in_fp32: True
    fused_add_norm: True
    bimamba_type: "v2"
    drop_path_rate: 0.1
    mamba_pos: True
    mamba_layers_orders: [ "xyz", "xzy", "yxz", "yzx", "zxy", "zyx", "hilbert", "z", "z-trans" ]
    use_order_prompt: True
    prompt_num_per_order: 6
    use_windows: True
    windows_size: [1024, 512, 256, 128]
    grid_size: 0.04
    combine_pos: True

  decoder_args:
    NAME: PointMambaDecoder
    encoder_channel_list: [ 96, 96, 192, 384, 768 ]
    decoder_channel_list: [ 384, 192, 96, 96 ]
    decoder_blocks: [ 1, 1, 1, 1 ]
    mamba_blocks: [ 0, 0, 0, 0 ]
    mamba_layers_orders: [ ]

  cls_args:
    NAME: SegHead
    global_feat: max,avg  # append global feature to each point feature
    num_classes: 13
    in_channels: null
    norm_args:
      norm: 'bn'

lr: 0.0001
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05

warmup_epochs: 5
min_lr: 1.0e-5

batch_size: 4
dataloader:
  num_workers: 8

dataset:
  common:
    NAME: S3DIS
    data_root: data/S3DIS/s3disfull
    test_area: 5
    voxel_size: 0.04
  train:
    split: train
    voxel_max: 24576
    loop: 30  # here, the training has been looped 30 times. therefore, the training epochs do not need much.
    presample: False